export interface Product {
  id: string
  name: string
  slug: string
  description: string
  price: number
  image: string
  category: string
  categorySlug: string
  featured: boolean
  bestSeller: boolean
  carousel?: boolean
  carouselOrder?: number
}

export const products: Product[] = [
  {
    id: "1",
    name: "Camisa Linen Classic",
    slug: "camisa-linen-classic",
    description: "Camisa de lino 100% natural. Fresca, transpirable y perfecta para el clima tropical.",
    price: 79.900,
    image: "/images/product-1.jpg",
    category: "Ropa",
    categorySlug: "ropa",
    featured: false,
    bestSeller: false,
  },
  {
    id: "2",
    name: "Jeans Slim Fit Premium",
    slug: "jeans-slim-fit-premium",
    description: "Jeans de algodón stretch con corte slim. Comodidad y estilo en una sola prenda.",
    price: 119.900,
    image: "/images/product-2.jpg",
    category: "Ropa",
    categorySlug: "ropa",
    featured: false,
    bestSeller: false,
  },
  {
    id: "3",
    name: "Polera Básica Algodón",
    slug: "polera-basica-algodon",
    description: "Polera de algodón peinado 180gsm. Corte clásico, cuello redondo reforzado.",
    price: 45.900,
    image: "/images/product-3.jpg",
    category: "Ropa",
    categorySlug: "ropa",
    featured: false,
    bestSeller: false,
  },
  {
    id: "4",
    name: "Falda Midi Elegante",
    slug: "falda-midi-elegante",
    description: "Falda midi de viscosa con caída fluida. Cintura elástica y bolsillos laterales.",
    price: 89.900,
    image: "/images/product-4.jpg",
    category: "Ropa",
    categorySlug: "ropa",
    featured: false,
    bestSeller: false,
  },
  {
    id: "5",
    name: "Bermudas Casual",
    slug: "bermudas-casual",
    description: "Bermudas de gabardina stretch. Largo a la rodilla, bolsillos funcionales.",
    price: 69.900,
    image: "/images/product-5.jpg",
    category: "Ropa",
    categorySlug: "ropa",
    featured: false,
    bestSeller: false,
  },
  {
    id: "6",
    name: "Camiseta Blanca Básica",
    slug: "camiseta-blanca-basica",
    description: "Camiseta esencial de algodón orgánico 160gsm. Corte regular, cuello redondo.",
    price: 35.900,
    image: "/images/product-6.jpg",
    category: "Imperdibles",
    categorySlug: "imperdibles",
    featured: false,
    bestSeller: false,
  },
  {
    id: "7",
    name: "Pantalón Negro Versátil",
    slug: "pantalon-negro-versatil",
    description: "Pantalón chino negro stretch. Funciona para oficina y ocasiones casuales.",
    price: 99.900,
    image: "/images/product-7.jpg",
    category: "Imperdibles",
    categorySlug: "imperdibles",
    featured: false,
    bestSeller: false,
  },
  {
    id: "8",
    name: "Chaqueta Denim Clásica",
    slug: "chaqueta-denim-clasica",
    description: "Chaqueta denim 12oz azul índigo. Corte recto, botones metálicos, bolsillos pecho.",
    price: 149.900,
    image: "/images/product-8.jpg",
    category: "Imperdibles",
    categorySlug: "imperdibles",
    featured: false,
    bestSeller: false,
  },
  {
    id: "9",
    name: "Vestido Negro Esencial",
    slug: "vestido-negro-esencial",
    description: "Vestido negro corte recto, largo midi. Tejido ponte roma que no se arruga.",
    price: 109.900,
    image: "/images/product-9.jpg",
    category: "Imperdibles",
    categorySlug: "imperdibles",
    featured: false,
    bestSeller: false,
  },
  {
    id: "10",
    name: "Suéter Gris Comfort",
    slug: "sueter-gris-comfort",
    description: "Suéter de punto medio en gris melange. Cuello redondo, puños y bajo acanalados.",
    price: 89.900,
    image: "/images/product-10.jpg",
    category: "Imperdibles",
    categorySlug: "imperdibles",
    featured: false,
    bestSeller: false,
  },
  {
    id: "11",
    name: "Traje Elegante Premium",
    slug: "traje-elegante-premium",
    description: "Traje dos piezas lana fría italiana. Corte moderno, forro completo, pantalón sin pinzas.",
    price: 299.900,
    image: "/images/product-11.jpg",
    category: "Colección Destacada",
    categorySlug: "coleccion-destacada",
    featured: false,
    bestSeller: false,
  },
  {
    id: "12",
    name: "Vestido Floral Exclusivo",
    slug: "vestido-floral-exclusivo",
    description: "Vestido midi estampado floral único. Seda viscosa, escote en V, manga abullonada.",
    price: 179.900,
    image: "/images/product-12.jpg",
    category: "Colección Destacada",
    categorySlug: "coleccion-destacada",
    featured: false,
    bestSeller: false,
  },
  {
    id: "13",
    name: "Camisa Premium Edición Limitada",
    slug: "camisa-premium-edicion-limitada",
    description: "Camisa popelín algodón egipcio 200 hilos. Cuenta con numeración exclusiva 1/100.",
    price: 129.900,
    image: "/images/product-13.jpg",
    category: "Colección Destacada",
    categorySlug: "coleccion-destacada",
    featured: false,
    bestSeller: false,
  },
  {
    id: "14",
    name: "Conjunto Deportivo Luxury",
    slug: "conjunto-deportivo-luxury",
    description: "Sudadera y jogger en algodón premium cepillado. Logo bordado, detalles reflectivos.",
    price: 199.900,
    image: "/images/product-14.jpg",
    category: "Colección Destacada",
    categorySlug: "coleccion-destacada",
    featured: false,
    bestSeller: false,
  },
  {
    id: "15",
    name: "Abrigo Invierno Designer",
    slug: "abrigo-invierno-designer",
    description: "Abrigo largo lana merino doble faz. Corte oversize, cuello solapa, bolsillos ocultos.",
    price: 249.900,
    image: "/images/product-15.jpg",
    category: "Colección Destacada",
    categorySlug: "coleccion-destacada",
    featured: false,
    bestSeller: false,
  },
  {
    id: "16",
    name: "Hoodie Urban Classic",
    slug: "hoodie-urban-classic",
    description: "Hoodie algodón 350gsm felpa interior. Capucha forrada, bolsillo canguro, puños acanalados.",
    price: 129.900,
    image: "/images/product-16.jpg",
    category: "Más Vendidos",
    categorySlug: "mas-vendidos",
    featured: false,
    bestSeller: false,
  },
  {
    id: "17",
    name: "Zapatillas Street Style",
    slug: "zapatillas-street-style",
    description: "Zapatillas retro runner. Suela EVA, upper mesh y piel, plantilla memory foam.",
    price: 159.900,
    image: "/images/product-17.jpg",
    category: "Más Vendidos",
    categorySlug: "mas-vendidos",
    featured: false,
    bestSeller: false,
  },
  {
    id: "18",
    name: "Gorra Snapback Frank",
    slug: "gorra-snapback-frank",
    description: "Gorra snapback 6 paneles. Frontal estructurado, visera plana, bordado 3D FrankStore.",
    price: 49.900,
    image: "/images/product-18.jpg",
    category: "Más Vendidos",
    categorySlug: "mas-vendidos",
    featured: false,
    bestSeller: false,
  },
  {
    id: "19",
    name: "Mochila Urban Pack",
    slug: "mochila-urban-pack",
    description: "Mochila 22L poliéster resistente al agua. Compartimento laptop 15\", organizador interno.",
    price: 89.900,
    image: "/images/product-19.jpg",
    category: "Más Vendidos",
    categorySlug: "mas-vendidos",
    featured: false,
    bestSeller: false,
  },
  {
    id: "20",
    name: "Chain Necklace Gold",
    slug: "chain-necklace-gold",
    description: "Collar cadena eslabones acero inoxidable baño oro 18k. Largo 50cm + 5cm extensión.",
    price: 39.900,
    image: "/images/product-20.jpg",
    category: "Más Vendidos",
    categorySlug: "mas-vendidos",
    featured: false,
    bestSeller: false,
  },
]

export const featuredProducts = products.filter((p) => p.featured)

export const categories = [
  { name: "Ropa", slug: "ropa", image: "/images/category-ropa.jpg" },
  { name: "Imperdibles", slug: "imperdibles", image: "/images/category-imperdibles.jpg" },
  { name: "Colección Destacada", slug: "coleccion-destacada", image: "/images/category-destacada.jpg" },
  { name: "Más Vendidos", slug: "mas-vendidos", image: "/images/category-mas-vendidos.jpg" },
]